// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagJYu1vkTK9sXQM38cHwsTResy-1mgdw',
    appId: '1:208543233592:web:d1aeb0e89c717c6e0e98cd',
    messagingSenderId: '208543233592',
    projectId: 'sociallogin-bb669',
    authDomain: 'sociallogin-bb669.firebaseapp.com',
    storageBucket: 'sociallogin-bb669.appspot.com',
    measurementId: 'G-K1K6QJPMCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKiCh5oVusLXYxPXEvErlLGBMmal9QKb0',
    appId: '1:208543233592:android:72dac00766bf912d0e98cd',
    messagingSenderId: '208543233592',
    projectId: 'sociallogin-bb669',
    storageBucket: 'sociallogin-bb669.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwXp3yidpPQzQiwyvu2p_oFH_gFXw5s8w',
    appId: '1:208543233592:ios:5281865dd703773e0e98cd',
    messagingSenderId: '208543233592',
    projectId: 'sociallogin-bb669',
    storageBucket: 'sociallogin-bb669.appspot.com',
    iosClientId: '208543233592-ggl31qh23li370tt1h9i94saj6il9pdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwXp3yidpPQzQiwyvu2p_oFH_gFXw5s8w',
    appId: '1:208543233592:ios:7b24118212e51ff10e98cd',
    messagingSenderId: '208543233592',
    projectId: 'sociallogin-bb669',
    storageBucket: 'sociallogin-bb669.appspot.com',
    iosClientId: '208543233592-s9njcrqq98325bb7no7e54ujk5qt5f60.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialLogin.RunnerTests',
  );
}
